export const prefixCategoryMap: Record<string, string> = {
  // ─── Color / Background ────────────────────────────────────────
  "bg-": "Color",
  "from-": "Color",
  "via-": "Color",
  "to-": "Color",
  "accent-": "Color",
  "color-": "Color",

  // ─── Typography ────────────────────────────────────────────────
  "text-": "Typography",
  "font-": "Typography",
  "tracking-": "Typography",
  "leading-": "Typography",
  "list-": "Typography",
  "align-": "Typography",
  "whitespace-": "Typography",
  "break-": "Typography",
  "decoration-": "Typography",
  "placeholder-": "Typography",
  "caret-": "Typography",
  "indent-": "Typography",
  "line-clamp-": "Typography",
  "hyphens-": "Typography",
  "word-": "Typography",
  uppercase: "Typography",
  lowercase: "Typography",
  capitalize: "Typography",
  "normal-case": "Typography",
  truncate: "Typography",
  antialiased: "Typography",
  "subpixel-antialiased": "Typography",
  italic: "Typography",
  "not-italic": "Typography",
  "lining-nums": "Typography",
  "oldstyle-nums": "Typography",
  "proportional-nums": "Typography",
  "tabular-nums": "Typography",
  "diagonal-fractions": "Typography",
  "stacked-fractions": "Typography",
  "slashed-zero": "Typography",
  "ordinal": "Typography",
  "normal-nums": "Typography",

  // ─── Spacing ───────────────────────────────────────────────────
  "p-": "Spacing",
  "px-": "Spacing",
  "py-": "Spacing",
  "ps-": "Spacing",
  "pe-": "Spacing",
  "pt-": "Spacing",
  "pr-": "Spacing",
  "pb-": "Spacing",
  "pl-": "Spacing",
  "m-": "Spacing",
  "mx-": "Spacing",
  "my-": "Spacing",
  "ms-": "Spacing",
  "me-": "Spacing",
  "mt-": "Spacing",
  "mr-": "Spacing",
  "mb-": "Spacing",
  "ml-": "Spacing",
  "space-x-": "Spacing",
  "space-y-": "Spacing",
  "space-x-reverse": "Spacing",
  "space-y-reverse": "Spacing",
  "gap-": "Spacing",
  "gap-x-": "Spacing",
  "gap-y-": "Spacing",

  // ─── Sizing ────────────────────────────────────────────────────
  "w-": "Sizing",
  "min-w-": "Sizing",
  "max-w-": "Sizing",
  "h-": "Sizing",
  "min-h-": "Sizing",
  "max-h-": "Sizing",
  "size-": "Sizing",

  // ─── Layout ────────────────────────────────────────────────────
  container: "Layout",
  "box-": "Layout",
  "columns-": "Layout",
  block: "Layout",
  "inline-block": "Layout",
  "inline-flex": "Layout",
  "inline-grid": "Layout",
  "inline-table": "Layout",
  inline: "Layout",
  flex: "Layout",
  grid: "Layout",
  table: "Layout",
  "table-": "Layout",
  "flow-root": "Layout",
  contents: "Layout",
  hidden: "Layout",
  "col-": "Layout",
  "row-": "Layout",
  "auto-cols-": "Layout",
  "auto-rows-": "Layout",
  "grid-cols-": "Layout",
  "grid-rows-": "Layout",
  "grid-flow-": "Layout",
  "place-": "Layout",
  "place-content-": "Layout",
  "place-items-": "Layout",
  "place-self-": "Layout",
  "justify-": "Layout",
  "justify-items-": "Layout",
  "justify-self-": "Layout",
  "items-": "Layout",
  "content-": "Layout",
  "self-": "Layout",
  "order-": "Layout",
  "float-": "Layout",
  "clear-": "Layout",
  "z-": "Layout",
  isolate: "Layout",
  "isolation-": "Layout",
  "inset-": "Layout",
  "inset-x-": "Layout",
  "inset-y-": "Layout",
  "start-": "Layout",
  "end-": "Layout",
  "top-": "Layout",
  "right-": "Layout",
  "bottom-": "Layout",
  "left-": "Layout",
  static: "Layout",
  fixed: "Layout",
  absolute: "Layout",
  relative: "Layout",
  sticky: "Layout",
  "overflow-": "Layout",
  "overflow-x-": "Layout",
  "overflow-y-": "Layout",
  "overscroll-": "Layout",
  "overscroll-x-": "Layout",
  "overscroll-y-": "Layout",
  "object-": "Layout",
  "aspect-": "Layout",
  "flex-": "Layout",
  "flex-row": "Layout",
  "flex-col": "Layout",
  "flex-wrap": "Layout",
  "flex-nowrap": "Layout",
  "flex-row-reverse": "Layout",
  "flex-col-reverse": "Layout",
  "flex-wrap-reverse": "Layout",
  "grow": "Layout",
  "grow-": "Layout",
  "shrink": "Layout",
  "shrink-": "Layout",
  "basis-": "Layout",
  "divide-": "Layout",
  "sr-only": "Accessibility",
  "not-sr-only": "Accessibility",

  // ─── Border ────────────────────────────────────────────────────
  "border-": "Border",
  "outline-": "Border",
  "ring-": "Border",
  "ring-offset-": "Border",
  "rounded-": "Border",
  rounded: "Border",
  "border-t": "Border",
  "border-r": "Border",
  "border-b": "Border",
  "border-l": "Border",
  "border-s": "Border",
  "border-e": "Border",
  "border-x": "Border",
  "border-y": "Border",

  // ─── Effects ───────────────────────────────────────────────────
  "shadow-": "Effect",
  shadow: "Effect",
  "shadow-inner": "Effect",
  "shadow-none": "Effect",
  "opacity-": "Effect",
  "mix-blend-": "Effect",
  "bg-blend-": "Effect",
  "backdrop-": "Effect",
  "drop-shadow-": "Effect",
  "grayscale": "Effect",
  "grayscale-": "Effect",
  "invert": "Effect",
  "invert-": "Effect",
  "sepia": "Effect",
  "sepia-": "Effect",
  "blur-": "Effect",
  "blur": "Effect",
  "brightness-": "Effect",
  "contrast-": "Effect",
  "hue-rotate-": "Effect",
  "saturate-": "Effect",
  "filter": "Effect",
  "filter-none": "Effect",
  "backdrop-blur-": "Effect",
  "backdrop-brightness-": "Effect",
  "backdrop-contrast-": "Effect",
  "backdrop-grayscale-": "Effect",
  "backdrop-hue-rotate-": "Effect",
  "backdrop-invert-": "Effect",
  "backdrop-opacity-": "Effect",
  "backdrop-saturate-": "Effect",
  "backdrop-sepia-": "Effect",

  // ─── Animation ─────────────────────────────────────────────────
  transition: "Animation",
  "transition-": "Animation",
  "duration-": "Animation",
  "ease-": "Animation",
  "delay-": "Animation",
  "animate-": "Animation",
  "will-change-": "Animation",

  // ─── Transform ─────────────────────────────────────────────────
  "scale-": "Transform",
  "scale-x-": "Transform",
  "scale-y-": "Transform",
  "rotate-": "Transform",
  "translate-": "Transform",
  "translate-x-": "Transform",
  "translate-y-": "Transform",
  "skew-": "Transform",
  "skew-x-": "Transform",
  "skew-y-": "Transform",
  "origin-": "Transform",
  transform: "Transform",
  "transform-": "Transform",
  "transform-gpu": "Transform",
  "transform-none": "Transform",

  // ─── Interactivity ─────────────────────────────────────────────
  "select-": "Interactivity",
  "pointer-events-": "Interactivity",
  resize: "Interactivity",
  "resize-": "Interactivity",
  "cursor-": "Interactivity",
  "touch-": "Interactivity",
  "touch-action-": "Interactivity",
  "scroll-": "Interactivity",
  "scroll-m-": "Interactivity",
  "scroll-p-": "Interactivity",
  "scroll-smooth": "Interactivity",
  "snap-": "Interactivity",
  visible: "Interactivity",
  invisible: "Interactivity",
  "appearance-": "Interactivity",
  "outline-none": "Interactivity",

  // ─── Accessibility ─────────────────────────────────────────────
  "forced-color-adjust-": "Accessibility",

  // ─── SVG ───────────────────────────────────────────────────────
  "stroke-": "SVG",
  "fill-": "SVG",

  // ─── Tables ────────────────────────────────────────────────────
  "border-collapse": "Table",
  "border-separate": "Table",
  "border-spacing-": "Table",
  "caption-": "Table",

  // ─── Background Utilities ──────────────────────────────────────
  "bg-none": "Color",
  "bg-gradient-": "Color",
  "bg-auto": "Color",
  "bg-cover": "Color",
  "bg-contain": "Color",
  "bg-fixed": "Color",
  "bg-local": "Color",
  "bg-scroll": "Color",
  "bg-clip-": "Color",
  "bg-repeat": "Color",
  "bg-no-repeat": "Color",
  "bg-repeat-": "Color",
  "bg-origin-": "Color",
  "bg-center": "Color",
  "bg-top": "Color",
  "bg-bottom": "Color",
  "bg-left": "Color",
  "bg-right": "Color",
};
